services:
  app:
    build: .
    ports:
      - "8502:8501"
    environment:
      - IN_DOCKER=true
    depends_on:
      - db  # Wait for MySQL container
    volumes:
      - .:/app
    networks:
      - space_truss_net
    restart: unless-stopped

  db:  # New MySQL service
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: space_truss_db_st
      MYSQL_USER: space_truss_db_st_user
      MYSQL_PASSWORD: 934
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - space_truss_net
    ports:
      - "3307:3306"  # Optional: Only include if you need external access

networks:
  space_truss_net:

volumes:
  mysql_data:  # Named volume for database persistence